#!/usr/bin/env bash
git pull
systemctl stop tmrc
npm ci
npm run build
ln -sf /opt/tmrc/tmrc.service /etc/systemd/system
systemctl daemon-reload
systemctl enable tmrc
systemctl start tmrc
systemctl status tmrc